# Generated by Django 2.1.7 on 2019-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=50)),
                ('restaurantLocation', models.CharField(max_length=50)),
                ('restaurantCity', models.CharField(max_length=10)),
                ('restaurantCusine', models.CharField(max_length=10)),
                ('restaurantCostForTwo', models.IntegerField()),
                ('restaurantRating', models.IntegerField()),
                ('restaurantRatingText', models.CharField(max_length=100)),
                ('restaurantRatingColor', models.CharField(max_length=10)),
                ('restaurantRatingVotes', models.IntegerField()),
                ('restaurantPhotosURL', models.URLField()),
                ('restaurantMenuURL', models.URLField()),
                ('restaurantImage', models.URLField()),
            ],
        ),
    ]
