# Generated by Django 2.1.7 on 2019-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=50)),
                ('restaurantAddress', models.CharField(max_length=100)),
                ('restaurantLocation', models.CharField(max_length=50)),
                ('restaurantCity', models.CharField(max_length=10)),
                ('restaurantCusine', models.CharField(max_length=10)),
                ('restaurantCostForTwo', models.CharField(max_length=10)),
                ('restaurantRating', models.CharField(max_length=10)),
                ('restaurantRatingText', models.CharField(max_length=100)),
                ('restaurantRatingColor', models.CharField(max_length=10)),
                ('restaurantRatingVotes', models.CharField(max_length=10)),
                ('restaurantImage', models.URLField()),
            ],
        ),
    ]
