# Generated by Django 2.1.7 on 2019-03-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=50)),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_summary.Restaurant')),
            ],
        ),
    ]
