# Generated by Django 2.1.7 on 2019-04-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_summary', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantCostForTwo',
            field=models.IntegerField(max_length=10),
        ),
    ]
