# Generated by Django 2.1.7 on 2019-04-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_summary', '0003_auto_20190416_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantCostForTwo',
            field=models.IntegerField(),
        ),
    ]
