# Generated by Django 2.1.7 on 2019-04-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_summary', '0004_auto_20190416_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantRatingVotes',
            field=models.IntegerField(),
        ),
    ]
