# Generated by Django 2.1.7 on 2019-03-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_summary', '0005_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
